import javax.swing.*;
import java.awt.*;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kaan
 */
public class EditBook extends javax.swing.JFrame {

    ArrayList<Genre> Genres;
    ArrayList<Book> Books;
    
    /**
     * Creates new form EditBook
     */
    public EditBook() {
        initComponents();
        
         Genres = new ArrayList<>();
        Books = new ArrayList<>();
        populateArrayList();
        
        
        String [] GenresArray = new String[Genres.size()];
        for (int i=0;i<Genres.size();i++)
        {
    GenresArray[i] = Genres.get(i).getGenre();
        }
        cbGenre.setModel(new javax.swing.DefaultComboBoxModel<>(GenresArray));
        
        String [] BooksArray = new String[Books.size()];
        for (int i=0; i<Books.size(); i++){
            BooksArray[i] = Books.get(i).getBooksName() + " " +
                    Books.get(i).getAuthorsName();
        }
        cbBook.setModel(new javax.swing.DefaultComboBoxModel<>(BooksArray));
        cbBook.setSelectedIndex(0);
        }
    
    public void populateArrayList(){
        AddBook.populateArrayList(Genres, Books);
    }
    
     public void saveBooksToFile(){
        try {
            FileOutputStream fileBook = new FileOutputStream("Books.dat");
            ObjectOutputStream outputFileBook = new ObjectOutputStream(fileBook);

            for (Book book : Books) {
                outputFileBook.writeObject(book);
            }
            outputFileBook.close();
            JOptionPane.showMessageDialog(null, "Action completed successfully!");
            this.dispose();
        } catch (IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold default-state="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel jLabel1 = new JLabel();
        cbBook = new javax.swing.JComboBox<>();
        JLabel jLabel2 = new JLabel();
        JLabel jLabel3 = new JLabel();
        tfBookName = new javax.swing.JTextField();
        tfAuthorName = new javax.swing.JTextField();
        JLabel jLabel6 = new JLabel();
        JButton jButton1 = new JButton();
        JButton jButton2 = new JButton();
        JLabel jLabel7 = new JLabel();
        cbGenre = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Choose book:");

        cbBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        cbBook.addActionListener(this::cbBookActionPerformed);

        jLabel2.setText("Books name :");

        jLabel3.setText("Author's name:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 18)); // NOI18N
        jLabel6.setText("Edit book");

        jButton1.setText("Delete");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Save");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel7.setText("Books genre:");

        cbGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbGenre.addActionListener(this::cbGenreActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(cbBook, javax.swing.GroupLayout.Alignment.LEADING, 0, 179, Short.MAX_VALUE)
                    .addComponent(tfBookName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfAuthorName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbGenre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addComponent(cbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBookActionPerformed
        // TODO add your handling code here:
        int selectedIndexBok = cbBook.getSelectedIndex();
        tfBookName.setText(Books.get(selectedIndexBok).getBooksName());
        tfAuthorName.setText(Books.get(selectedIndexBok).getAuthorsName());
        
        Genre genre = Books.get(selectedIndexBok).getTypeOfBook();
        int bokGenreIndex=0;
        System.out.println(Genres);
        for (int i=0; i<Genres.size(); i++){
            System.out.println(genre);
            if (genre.getGenre().equals(Genres.get(i).getGenre())){
                bokGenreIndex = i;
                
                break;
            }                
        }
        cbGenre.setSelectedIndex(bokGenreIndex);
    }//GEN-LAST:event_cbBookActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (this.tfBookName.getText().isEmpty() || 
                this.tfAuthorName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all the details");
        } else {
            int selectedIndexBok = cbBook.getSelectedIndex();
            Books.get(selectedIndexBok).setBooksName(tfBookName.getText().trim());
            Books.get(selectedIndexBok).setAuthorsName(tfAuthorName.getText().trim());
            
            
            Genre genre = Genres.get(cbGenre.getSelectedIndex());
            Books.get(selectedIndexBok).setTypeOfBook(genre);
            
            saveBooksToFile();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedIndexBok = cbBook.getSelectedIndex();
        Books.remove(selectedIndexBok);
        saveBooksToFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold default-state="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditBook().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbBook;
    private javax.swing.JComboBox<String> cbGenre;
    private javax.swing.JTextField tfAuthorName;
    private javax.swing.JTextField tfBookName;
    // End of variables declaration//GEN-END:variables
}
